### ISSUE TITLE
Test with how many rows?

### ISSUE THREAD

**Issue by ghost** [BernhardSchlegel/SQL-dumper#2]
Hi,

 Can you please let us know, with how many millions rows you have tested this cmd to export? I need to export 3 Million data, how much time it will take to export using the SQL-dumper?

Thanks,
Chandru

**Comment by BernhardSchlegel** [comment]
Should be a matter of minutes - depending on your number of columns. This is limited by the throughput your harddrive and/or your SQL-Server and/or your Network interface - not the SQL dumper.
